name: Generate Metrics
on:
  schedule: [{ cron: "0 6 * * *" }] # her sabah
  workflow_dispatch:
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ramazankudret
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul
          filename: metrics.svg
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css
          plugin_achievements: yes
          plugin_achievements_display: compact
