name: Generate Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ramazankudret
          template: classic
          base: header, activity, community, repositories, metadata
          filename: metrics.svg
          config_timezone: Europe/Istanbul
