name: Recent Activity

on:
  schedule:
    - cron: "0 * * * *"   # her saat başı çalışır
  workflow_dispatch:       # manuel tetikleme

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          GH_USERNAME: ramazankudret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_LINES: 10
