name: Recent Activity
on:
  schedule:
    - cron: "0 * * * *"        # saat başı
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GH_USERNAME: ramazankudret
          MAX_LINES: 10
